# Generated by Django 5.1.1 on 2024-10-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('system', models.CharField(max_length=50)),
                ('mineral', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ore_capacity', models.IntegerField()),
                ('crew_capacity', models.IntegerField()),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('SC', 'Sub-Capital'), ('C', 'Capital')], max_length=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='vastro.mininglocations')),
            ],
        ),
    ]
